language: python
branches:
  only:
  - master
install:
- pip install pelican
- pip install ghp-import
- pip install Markdown
script:
- make publish
- make github 2> /dev/null
env:
  global:
    secure: DFCVZeuf1/8csaN3s5QTFk8CvKuoYI3bKdzewCEdtzaxFIqceSuFtgtQdl81Nzl64Gm6Fb/SgfORDckbVfwD/YoYjlh9mV3peTH7f285Yn+XPVGCVCaLsYsiZ21B5wQDDVkh7Zb2mirMgkhfILL5J+9acEGFHR3pUVwU1tlHlBE=
